[package]
name = "log-analyser"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[[bin]]
name = "log-normalizer"
path = "src/main.rs"

[dependencies]
sqlx = { version = "0.3", default_features = false, features = ["macros", "postgres", "json", "runtime-tokio", "chrono"] }
dotenv = "0.15.0"
main_error = "0.1.0"
tokio = { version = "0.2.13", features = ["macros", "time"] }
reqwest = { version = "0.10.4", features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
steamid-ng = "0.3.4"
test-case = "1.0.0"
tracing = "0.1.33"
tracing-subscriber = "0.3.11"

[replace]
"sqlx-macros:0.3.5" = { git = "https://github.com/icewind1991/sqlx", branch = "type_override-exprgroup-0.3.5" }